- name: "Make elastic dirs"
  file:
    path: /media/hdd1/data/elasticsearch/data
    state: directory
    mode: 0777

- name: "Starting elastic as a standalone container"
  docker_container:
    name: "xver_elastic"
    image: "docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4"
    state: started
    restart_policy: always
    ports:
      - "9200:9200"
      - "9300:9300"
    env: "cluster.name=xver-cluster"
    volumes:
      - /media/hdd1/data/elasticsearch/data:/usr/share/elasticsearch/data
    log_driver: syslog
    log_opt:
      syslog-address: "udp://{{ syslog_destination }}"
      syslog-format: "rfc3164"
      tag: xvers/elastic