# Настройка окружения для Linux`а

- name: "Install resolv.conf"
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0644

# Добавляем сторонние репозитории при необходимости
# Сюда добавляются только сторонние репозитории софта который необходим на всех серверах
# Пример:
#- set_fact:
#    linux_repository_list:
#      - "deb http://deb.debian.org/debian {{ansible_distribution_release|lower}} main contrib non-free"
#      - "deb http://deb.debian.org/debian {{ansible_distribution_release|lower}}-updates main contrib non-free"
#      - "deb http://security.debian.org/ {{ansible_distribution_release|lower}}/updates main contrib non-free"
#
#- name: Linux additional repositories setup
#  apt_repository: repo={{ item }} state=present
#  with_items: "{{ linux_repository_list }}"

# Определяем типовой софт
- name: "Init list of linux common software"
  set_fact:
    linux_soft_list:
      - mc
      - gawk
      - zsh
      - wget
      - curl
      - vim
      - htop
      - tshark
      - ca-certificates
      - apt-transport-https
      - bridge-utils
      - ntpdate
      - jq

# Устанавливаем типовой софт для семейства типа "Debian"
- name: "Install linux common software"
  name: Linux common software install
  become: yes
  apt: name={{ item }} state=present
  with_items: "{{ linux_soft_list }}"
  when: ansible_os_family == "Debian"

- name: "Setup firewall rules"
  include_tasks: iptables.yml

# Сбрасываем индивидуальные настройки .zshrc
- name: "List homes"
  command: "ls /home"
  register: homes

- name: "Download shared .zshrc config"
  get_url:
    url: https://raw.githubusercontent.com/golovanovsv/configs/master/.zshrc
    dest: "/home/{{ item }}/.zshrc.tmp"
    mode: 0644
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ homes.stdout_lines }}"

- name: "Update .zshrc config"
  copy:
    src: "/home/{{ item }}/.zshrc.tmp"
    dest: "/home/{{ item }}/.zshrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  with_items: "{{ homes.stdout_lines }}"

- name: "Remove temp .zshrc config"
  file:
    state: absent
    path: "/home/{{ item }}/.zshrc.tmp"
  with_items: "{{ homes.stdout_lines }}"

# Обновляем параметры zshell
- name: "Download shared zshrc config"
  get_url:
    url: https://raw.githubusercontent.com/golovanovsv/configs/master/.zshrc
    dest: "{{ zshrc_path }}.tmp"
    mode: 0644
    force: yes

- name: "Update global zshrc config"
  copy:
    src: "{{ zshrc_path }}.tmp"
    dest: "{{ zshrc_path }}"

- name: "Remove temp zhrc config"
  file:
    state: absent
    path: "{{ zshrc_path }}.tmp"
