# Настройка окружения для Linux`а

# Добавляем сторонние репозитории при необходимости
# Пример:
#- set_fact:
#    linux_repository_list:
#      - "deb http://deb.debian.org/debian {{ansible_distribution_release|lower}} main contrib non-free"
#      - "deb http://deb.debian.org/debian {{ansible_distribution_release|lower}}-updates main contrib non-free"
#      - "deb http://security.debian.org/ {{ansible_distribution_release|lower}}/updates main contrib non-free"
#
#- name: Linux additional repositories setup
#  apt_repository: repo={{ item }} state=present
#  with_items: "{{ linux_repository_list }}"

# Определяем типовой софт
- set_fact:
    linux_soft_list:
      - mc
      - gawk
      - zsh
      - wget
      - curl
      - vim
      - htop
      - tshark
      - ca-certificates
      - apt-transport-https
      - bridge-utils

# Устанавливаем типовой софт для семейства типа "Debian"
- name: Linux common software install
  become: yes
  apt: name={{ item }} state=present
  with_items: "{{ linux_soft_list }}"
  when: ansible_os_family == "Debian"

# Настраиваем параметры zshell
- name: zshrc settings
  become: yes
  copy:
    src: zshrc
    dest: "{{ zshrc_path }}"