- set_fact:
    server_interface: "eth0"

- name: "Accept IPv4 all for setup"
  iptables:
    chain: INPUT
    ip_version: ipv4
    policy: ACCEPT

- name: "Accept IPv6 all for setup"
  iptables:
    chain: INPUT
    ip_version: ipv6
    policy: ACCEPT

- name: "Flush iptables for setup"
  command: "{{item}}"
  with_items:
    - 'iptables -t filter -F INPUT'
    - 'ip6tables -t filter -F INPUT'

- name: "Setup local traffic"
  iptables:
    chain: INPUT
    table: filter
    ip_version: "{{ item }}"
    in_interface: "!{{ server_interface }}"
    jump: ACCEPT
  with_items: ["ipv4", "ipv6"]

- name: "Setup established input"
  iptables:
    chain: INPUT
    table: filter
    ip_version: "{{ item }}"
    in_interface: "{{ server_interface }}"
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  with_items: ["ipv4", "ipv6"]

- name: "Setup IPv4 protocols rules (INPUT)"
  iptables:
    chain: INPUT
    table: filter
    in_interface: "{{ server_interface }}"
    ip_version: ipv4
    protocol: "{{ item.proto }}"
    destination_port: "{{ item.port }}"
    ctstate: NEW
    jump: ACCEPT
    state: present
  with_items: "{{ accepted_rules }}"

- name: "Setup IPv4 sources rules (INPUT)"
  iptables:
    chain: INPUT
    table: filter
    in_interface: "{{ server_interface }}"
    ip_version: ipv4
    source: "{{ item }}"
    jump: ACCEPT
  with_items: "{{ accepted_sources_ipv4}}"

- name: "Setup IPv6 protocols rules (INPUT)"
  iptables:
    chain: INPUT
    table: filter
    in_interface: "{{ server_interface }}"
    ip_version: ipv6
    protocol: "{{ item.proto }}"
    destination_port: "{{ item.port }}"
    ctstate: NEW
    jump: ACCEPT
    state: present
  with_items: "{{ accepted_rules }}"

- name: "Setup IPv6 sources rules (INPUT)"
  iptables:
    chain: INPUT
    table: filter
    in_interface: "{{ server_interface }}"
    ip_version: ipv6
    source: "{{ item }}"
    jump: ACCEPT
  with_items: "{{ accepted_sources_ipv6 }}"

- name: "Drop IPv4 all"
  iptables:
    chain: INPUT
    ip_version: ipv4
    policy: ACCEPT

- name: "Drop IPv6 all"
  iptables:
    chain: INPUT
    ip_version: ipv6
    policy: ACCEPT