- name: "Installing ceph-mon"
  apt: name=ceph-mon state=latest

- set_fact:
    monitor_name: "{{ ansible_hostname }}"

- name: "Creating monitor dirs"
  file:
    path: "{{ item }}"
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"
    recurse: true
  with_items:
    - "/var/lib/ceph/tmp"
    - "/var/lib/ceph/mon"
    - "/var/run/ceph"

- name: "Creating monitor initial keyring"
  command: ceph-authtool /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }} --create-keyring --name=mon. --add-key={{ monitor_secret }} --cap mon 'allow *'
  args:
    creates: /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }}

- name: "Set keyring permissions"
  file:
    path: /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }}
    owner: "ceph"
    group: "ceph"
    mode: "0600"

- name: "Create custom admin keyring"
  command: "ceph-authtool /etc/ceph/{{ cluster }}.client.admin.keyring --create-keyring --name=client.admin --add-key={{ admin_secret }} --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow' --cap mgr 'allow *'"
  args:
    creates: /etc/ceph/{{ cluster }}.client.admin.keyring
  register: create_custom_admin_secret

- name: "Set admin keyring permissions"
  file:
    path: "/etc/ceph/{{ cluster }}.client.admin.keyring"
    state: file
    owner: "ceph"
    group: "ceph"
    mode: "0600"

- name: "Import admin keyring into mon keyring"
  command: ceph-authtool /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }} --import-keyring /etc/ceph/{{ cluster }}.client.admin.keyring

- name: "Monitor mkfs with keyring"
  become: true
  become_user: ceph
  command: ceph-mon --cluster {{ cluster }} --mkfs -i {{ monitor_name }} --fsid {{ ceph_fsid }} --keyring /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }}

- name: "Generate systemd unit file"
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-mon.service.j2"
    dest: /etc/systemd/system/ceph-mon@{{ monitor_name }}.service
    owner: "root"
    group: "root"
    mode: "0644"
  register: unit_file

- debug:
    var: unit_file

- name: "Reload systemd configuration if needed"
  systemd: daemon_reload=yes
  when: unit_file.changed == true

- name: start the monitor service
  service:
    name: ceph-mon@{{ monitor_name }}
    state: started
    enabled: yes