- file:
    path: "{{ item }}"
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"
  with_items:
    - "/var/lib/ceph/tmp"

- set_fact:
    monitor_name: "{{ ansible_hostname }}"

- name: create monitor initial keyring
  command: ceph-authtool /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }} --create-keyring --name=mon. --add-key={{ monitor_secret }} --cap mon 'allow *'
  args:
    creates: /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }}

- name: set key permissions
  file:
    path: /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }}
    owner: "ceph"
    group: "ceph"
    mode: "0600"

- name: create monitor directory
  file:
    path: /var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }}
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"
    recurse: true

- name: create custom admin keyring
  command: "ceph-authtool /etc/ceph/{{ cluster }}.client.admin.keyring --create-keyring --name=client.admin --add-key={{ admin_secret }} --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow' --cap mgr 'allow *'"
  args:
    creates: /etc/ceph/{{ cluster }}.client.admin.keyring
  register: create_custom_admin_secret

- name: set ownership of admin keyring
  file:
    path: "/etc/ceph/{{ cluster }}.client.admin.keyring"
    state: file
    owner: "ceph"
    group: "ceph"
    mode: "0600"

- name: import admin keyring into mon keyring
  command: ceph-authtool /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }} --import-keyring /etc/ceph/{{ cluster }}.client.admin.keyring

- name: ceph monitor mkfs with keyring
  become: true
  command: ceph-mon --cluster {{ cluster }} --mkfs -i {{ monitor_name }} --fsid {{ ceph_fsid }} --keyring /var/lib/ceph/tmp/keyring.mon.{{ monitor_name }}
  args:
    creates: /var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }}/keyring

- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-mon.service.j2"
    dest: /etc/systemd/system/ceph-mon@{{ monitor_name }}.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: start the monitor service
  service:
    name: ceph-mon@{{ monitor_name }}
    state: stopped
    enabled: no