- name: "Installing ceph-mon"
  apt: name=ceph-mon state=latest

- set_fact:
    monitor_name: "{{ ansible_hostname }}"

- name: "Creating mon. dirs"
  file:
    path: "{{ item }}"
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"
    recurse: true
  with_items:
    - "/var/run/ceph"
    - "/var/lib/ceph/mon"
    - "/var/lib/ceph/tmp"

- name: "Creating mon. keyring"
  command: ceph-authtool /var/lib/ceph/tmp/keyring --create-keyring --name=mon. --add-key={{ mon_secret }} --cap mon 'allow *'
  args:
    creates: /var/lib/ceph/tmp/keyring

- name: "Set mon. keyring permissions"
  file:
    path: /var/lib/ceph/tmp/keyring
    owner: "ceph"
    group: "ceph"
    mode: "0600"

- name: "Create admin. keyring"
  command: "ceph-authtool /etc/ceph/{{ cluster }}.client.admin.keyring --create-keyring --name=client.admin --add-key={{ admin_secret }} --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *'"
  args:
    creates: /etc/ceph/{{ cluster }}.client.admin.keyring

- name: "Set admin. keyring permissions"
  file:
    path: "/etc/ceph/{{ cluster }}.client.admin.keyring"
    state: file
    owner: "ceph"
    group: "ceph"
    mode: "0600"

- name: "Import admin. keyring into mon. keyring"
  command: ceph-authtool /var/lib/ceph/tmp/keyring --import-keyring /etc/ceph/{{ cluster }}.client.admin.keyring

- name: "mon. mkfs"
  become_user: ceph
  command: ceph-mon --cluster {{ cluster }} --mkfs -i {{ monitor_name }} --fsid {{ ceph_fsid }} --keyring /var/lib/ceph/tmp/keyring

- name: "Generate systemd unit file"
  template:
    src: "{{ role_path }}/templates/ceph-mon.service.j2"
    dest: /etc/systemd/system/ceph-mon@{{ monitor_name }}.service
    owner: "root"
    group: "root"
    mode: "0644"
  register: unit_file

- name: "Reload systemd configuration if needed"
  systemd: daemon_reload=yes
  when: unit_file.changed == true

- name: "Start the mon. service"
  service:
    name: ceph-mon@{{ monitor_name }}
    state: started
    enabled: yes
